### PR TITLE
Align terminal colors

### PR DESCRIPTION
**Pull request by svipas**
https://github.com/rmehri01/onenord.nvim/blob/main/extras/warp/one_nord.yaml

### CODE REVIEW

**Comment by Uaitt** [comment]
Hey @svipas, I am not the main maintainer but I think I can add something.

I looked at the various extra configurations in the `onenord.nvim` repo, and I have to say the the colors do not match completely between terminals :thinking: 

Take, for example, the configuration for [Kitty](https://github.com/rmehri01/onenord.nvim/blob/main/extras/kitty/onenord.conf) (which I use :cat:). This config completely matches the current one!

I think that, before continuing, we should ask @rmehri01 if there's a reason colors differ across terminal emulators (and even across editors - I have found the JetBrains colors slightly tweaked compared to the Neovim ones).

Hope this helps :smiley:

**Comment by svipas** [comment]
I would love to have colors like in my PR (also they match Warp terminal), because they are not so bright and since I have astigmatism it helps because they are less blurry. But of course it is up to maintainer, I can easily fork and have my own customizations on top.

**Comment by Uaitt** [comment]
You made a good point! :smile: It's ok for me.

I have one more point to add however. Since @s1e2b3i4 is working on PR #5, I think we should wait to look at all of your PRs. We are probably going to convert the JSON into a YAML, and you are defining colors that do not seem to exist in the [fixed color palette](https://github.com/s1e2b3i4/onenord-vscode/pull/5/files#diff-bd0f139d54d7ae5571283ee469d2015a4914f3f95c8a625fdea02db70986b76d) that @s1e2b3i4 chose. This will probably cause some issues later on :sweat_smile: 

I think the right approach now would be to:
1. wait that PR #5 gets merged into main.
2. revert the commit in all of your open PRs, and modify the new YAML instead, by adding any color that you find necessary in the fixed color palette.

WDYT? :smile:

**Comment by s1e2b3i4** [comment]
Thanks for the contribution!
@Uaitt was right, the confusion with the colors comes from the fact that the terminal colors differ slightly in the different implementations.

**Pull request merged**
